<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="chassis_length" value="0.80"/>
    <xacro:property name="chassis_width" value="0.48"/>
    <xacro:property name="chassis_height" value="0.57"/>
    <xacro:property name="chassis_mass" value="50.0"/>
    <xacro:property name="main_wheel_radius" value="0.17"/>
    <xacro:property name="main_wheel_thickness" value="0.07"/>
    <xacro:property name="main_wheel_mass" value="2.0"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.24"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="small_wheel_radius" value="0.11"/>
    <xacro:property name="small_wheel_thickness" value="0.065"/>
    <xacro:property name="small_wheel_mass" value="0.1"/>
    
    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${main_wheel_radius}" length="${main_wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${main_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${main_wheel_mass}" length="${main_wheel_thickness}" radius="${main_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>




    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
       <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${main_wheel_radius}" length="${main_wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${main_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${main_wheel_mass}" length="${main_wheel_thickness}" radius="${main_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

<!-- Front RIGHT WHEEL LINK -->

   
   <joint name="front_right_swivel_joint" type="continuous">
      <axis xyz="0 0 1"/>
      <parent link="base_link"/>
      <child link="front_right_swivel"/>
      <origin rpy="0 0 0" xyz="0.54 -${chassis_width/2} -${main_wheel_radius - small_wheel_radius}"/>
      <dynamics damping="0.0" friction="0.01" />
    </joint>

   <link name="front_right_swivel">
      <visual>
        <geometry>
          <cylinder length="0.065" radius="0.01"/>
        </geometry>
        <material name="white">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.065" radius="0.01"/>
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="0.1" length="0.065" radius="0.01">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
    </link>

   <gazebo reference="front_right_swivel">
        <material>Gazebo/White</material>
   </gazebo>

   <joint name="front_right_wheel_joint" type="continuous">
      <axis xyz="0 0 1"/>
      <parent link="front_right_swivel"/>
      <child link="front_right_wheel"/>
      <origin rpy="1.57075 0 0" xyz="0.065 0 0"/>
      <dynamics damping="0.0" friction="0.01" />
   </joint>

   <link name="front_right_wheel">
      <visual>
        <geometry>
          <cylinder length="${small_wheel_thickness}" radius="${small_wheel_radius}"/>
        </geometry>
        <material name="white">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${small_wheel_thickness}" radius="${small_wheel_radius}"/>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>0.01</mu>
              <mu2>0.01</mu2>
            </ode>
          </friction>
        </surface>
      </collision>
      <xacro:inertial_cylinder mass="${small_wheel_mass}" length="${small_wheel_thickness}" radius="${small_wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
   </link>

   <gazebo reference="front_right_wheel">
        <material>Gazebo/Blue</material>
   </gazebo>   

<!-- Front Left WHEEL LINK -->

   <joint name="front_left_swivel_joint" type="continuous">
      <axis xyz="0 0 1"/>
      <parent link="base_link"/>
      <child link="front_left_swivel"/>
      <origin rpy="0 0 0" xyz="0.54 ${chassis_width/2} -${main_wheel_radius - small_wheel_radius}"/>
      <dynamics damping="0.0" friction="0.01" />
   </joint>

   <link name="front_left_swivel">
      <visual>
        <geometry>
          <cylinder length="0.065" radius="0.01"/>
        </geometry>
        <material name="white">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="0.065" radius="0.01"/>
        </geometry>
      </collision>
      <xacro:inertial_cylinder mass="0.1" length="0.065" radius="0.01">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
   </link>

   <gazebo reference="front_left_swivel">
        <material>Gazebo/White</material>
   </gazebo>

   <joint name="front_left_wheel_joint" type="continuous">
      <axis xyz="0 0 -1.0"/>
      <parent link="front_left_swivel"/>
      <child link="front_left_wheel"/>
      <origin rpy="-1.57075 0 0" xyz="0.065 0 0"/>
      <dynamics damping="0.0" friction="0.01" />
   </joint>

   <link name="front_left_wheel">
      <visual>
        <geometry>
          <cylinder length="${small_wheel_thickness}" radius="${small_wheel_radius}"/>
        </geometry>
        <material name="white">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${small_wheel_thickness}" radius="${small_wheel_radius}"/>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>0.01</mu>
              <mu2>0.01</mu2>
            </ode>
          </friction>
        </surface>
      </collision>
      <xacro:inertial_cylinder mass="${small_wheel_mass}" length="${small_wheel_thickness}" radius="${small_wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>
   </link>

   <gazebo reference="front_left_wheel">
        <material>Gazebo/Blue</material>
   </gazebo>

</robot>